version: "3.8"

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - fastapi
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  fastapi:
    build: .
    container_name: fastapi
    ports:
      - "80:80"
    networks:
      - fastapi
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

networks:
  fastapi:
    driver: bridge

volumes:
  postgres_data:
    # This is a named volume used by the postgres service to persist data
